[project]
name = "water_column_sonar_catalog"
version = "26.2.0"
authors = [
    { name = "Rudy Klucik", email = "rudy.klucik@noaa.gov" },
]
maintainers = [
    { name = "Rudy Klucik", email = "rudy.klucik@noaa.gov" },
]
description = "STAC Catalog for Water Column Sonar Data"
keywords = ["ocean", "sonar", "water column"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python"
]
readme = "README.md"
requires-python = ">=3.12"
license = "MIT"
license-files = ["LICENSE"]

# uv sync --all-groups --upgrade
dependencies = [
    "geopandas",
    "numpy",
    "pandas",
    "pystac",
    "shapely",
]

# uv sync --all-groups --upgrade
[dependency-groups]
dev = [
    "bandit[toml]",
    "build",
    "pre-commit",
    "pytest",
    "pytest-cov",
    "ruff",
    "tqdm",
]

[project.urls]
Homepage = "https://echo.fish"
Repository = "https://github.com/CI-CMG/water-column-sonar-catalog"
Documentation = "https://github.com/CI-CMG/water-column-sonar-catalog"
Issues = "https://github.com/CI-CMG/water-column-sonar-catalog/issues"

[tool.bandit]
exclude_dirs = ["tests"]

[tool.pre-commit-hooks.bandit]
exclude = ["*/tests/*"]
